openapi: 3.0.3
info:
  title: Loan Service API
  description: 'Актуализировано: 6 марта 2025'
  version: '0.0.4'
servers:
  - url: '/api/loan-service'

paths:
  /v1/tariffs:
    get:
      description: 'Для сотрудников'
      summary: 'Получение тарифов'
      tags:
        - 'Тарифы'
      responses:
        '200':
          description: 'Тарифы'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tariff'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      description: 'Для сотрудников'
      summary: 'Создание тарифа'
      tags:
        - 'Тарифы'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                interestRate:
                  type: integer
                  format: double
              required:
                - name
                - interestRate
      responses:
        '201':
          description: 'Тариф успешно создан'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tariff'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /v1/tariffs/{tariffId}:
    parameters:
      - in: path
        name: tariffId
        required: true
        schema:
          type: string
          format: uuid

    put:
      description: 'Для сотрудников'
      summary: 'Изменение тарифа'
      tags:
        - 'Тарифы'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                interestRate:
                  type: integer
                  format: double
              required:
                - name
                - interestRate
      responses:
        '201':
          description: 'Тариф успешно изменен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tariff'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      description: 'Для сотрудников'
      summary: 'Удаление тарифа'
      tags:
        - 'Тарифы'
      responses:
        '204':
          description: 'Тариф удален успешно'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /v1/loans:
    get:
      description: 'Для сотрудников'
      summary: 'Получение кредитов'
      tags:
        - 'Кредиты'
      responses:
        '200':
          description: 'Кредиты'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Loan'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      description: 'Для клиента. Минимальная сумма равна 1. Дата конца должна быть больше даты начала'
      summary: 'Взятие кредита'
      tags:
        - 'Кредиты'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                tariffId:
                  type: string
                  format: uuid
                bankAccountId:
                  type: string
                  format: uuid
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                sum:
                  type: integer
                  format: double
              required:
                - tariffId
                - bankAccountId
                - startDate
                - endDate
                - sum
      responses:
        '201':
          description: 'Кредит успешно создан'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Loan'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /v1/loans/{userId}:
    parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: 'Получение кредитов пользователя'
      tags:
        - 'Кредиты'
      responses:
        '200':
          description: 'Кредиты'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Loan'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /v1/loans/{loanId}:
    parameters:
      - in: path
        name: loanId
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: 'Получение кредита'
      tags:
        - 'Кредиты'
      responses:
        '200':
          description: 'Кредит'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Loan'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      description: 'Для клиентов'
      summary: 'Погашение кредита'
      tags:
        - 'Кредиты'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                sum:
                  type: integer
                  format: double
              required:
                - sum
      responses:
        '201':
          description: 'Кредит успешно погашен'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Loan'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Error:
      properties:
        code:
          type: string
        message:
          type: string
          nullable: true
      required:
        - code

    Tariff:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        interestRate:
          type: integer
          format: double
      required:
        - id
        - name
        - interestRate

    Loan:
      properties:
        id:
          type: string
          format: uuid
        tariff:
          $ref: '#/components/schemas/Tariff'
        bankAccountId:
          type: string
          format: uuid
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        paidSum:
          type: integer
          format: double
        monthlyPayment:
          type: integer
          format: double
        debt:
          type: integer
          format: double
      required:
        - id
        - tariff
        - bankAccountId
        - startDate
        - endDate
        - paidSum
        - monthlyPayment
        - debt

  responses:
    InternalServerError:
      description: 'Internal Server Error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 'InternalServerError'
            message: 'Something went wrong'

    BadRequestError:
      description: 'Bad Request Error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 'InvalidUUID'
            message: 'Provided invalid UUID'

    NotFoundError:
      description: 'Not Found Error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 'NotFoundError'
            message: 'Loan not found'